src/views/predict/models.py
#src\views\predict\models.py

from src.extensions import db
from src.views.user.models import User

# Define the News model
class News(db.Model):
    id = db.Column(db.String(64), primary_key=True)
    text = db.Column(db.Text, nullable=False)
    result = db.Column(db.String(10), nullable=False)
    user_id = db.Column(db.String(64), db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"News('{self.text}', '{self.result}')"


def get_news_result(user_id, news_id):
    # Assuming you have a 'User' model
    user = User.query.get(user_id)

    # Fetch the news result based on user_id and news_id
    news = News.query.filter_by(id=news_id, user=user).first()

    if news:
        return news.result
    else:
        return None

src/views/user/models.py
# src\views\user\models.py

from src.extensions import db, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)



# Define the User model
class User(db.Model, UserMixin):
    id = db.Column(db.String(64), primary_key=True) 
    name = db.Column(db.String(100), nullable=False) 
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(256), nullable=False) 
    # Define a relationship between the User and News models
    news = db.relationship('News', backref='user', lazy=True)

    def __repr__(self):
        return f"User('{self.name}', '{self.email}')"

#We also define a relationship between the `User` and `News` models. This allows us to retrieve all news articles written by a specific user. The `backref` parameter in the `db.relationship` function allows us to access the user who wrote a specific news article from the news article object. The `lazy` parameter determines how the related objects are loaded from the database. In this case, we set it to `True` to load the related objects laz

src/views/predict/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PredictionInputForm(FlaskForm):
    news = TextAreaField('News', validators=[DataRequired()])
    submit = SubmitField('Check News')

    def __repr__(self):
        return f"PredictionInputForm({self.news})"

src/__init__.py
#src\__init__.py

from flask import Flask
from dotenv import load_dotenv
from .views import init_app_blueprints
from .extensions import db, bcrypt, login_manager

from .views.user.models import User

load_dotenv()

def init_db(app):
    # Bind the SQLAlchemy object to your Flask app
    db.init_app(app)
    # Check if the database and tables exist, and create them if not
    with app.app_context():
        db.create_all()
        # TODO: Remove this, dummy user
        if not User.query.get('1'):
            user = User(user_id = '1', name='John Doe', email='john@example.com', password='password')
            db.session.add(user)
            db.session.commit()


def create_app(config_file):
    app = Flask(__name__)

    #Load configurations
    app.config.from_pyfile(config_file)

    #Register Blueprints i.e initializing routes
    init_app_blueprints(app)

    # Initialize extensions 
    init_db(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    
    return app

src/views/__init__.py
from .home import home_bp
from .predict.routes import predict_bp
from .auth.routes import auth_bp
from .user.routes import user_bp

def init_app_blueprints(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(predict_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(user_bp)
    return app

src/views/home/__init__.py
from flask import Blueprint, render_template
 
home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def home():
    return render_template('home/home_view.html')

src/views/predict/__init__.py
from flask import Blueprint
 
predict_bp = Blueprint('predict', __name__, url_prefix='/predict')

src/views/predict/routes.py
#  src\views\predict\routes.py

import uuid
from flask import render_template, redirect, url_for, current_app, request
from flask_login import login_required
from . import predict_bp
from .forms import PredictionInputForm
from .utils import determine_news_fake
from .models import News, get_news_result
from src.extensions import db

# TODO: Protect this route when not in session
@predict_bp.route('/', methods = ['GET', 'POST'])
@login_required
def predict():
    form = PredictionInputForm()
    if form.validate_on_submit():
        print(form.news.data)
        input_news = form.news.data

        # Send the news to model to check whether it is real or fake
        result = determine_news_fake(input_news)
        print(result)
        
        news_id = str(uuid.uuid4())
        with current_app.app_context():
            news = News(id=news_id, text=input_news, result=result, user_id='1')

            # Add the news to the database
            db.session.add(news)
            db.session.commit()

        # TODO: Should pass user_id?
        return redirect(url_for('predict.result', user_id='1', news_id=news_id))
        

    return render_template('predict/predict_view.html', form = form)

# TODO: Protect this route even in session
@predict_bp.route('/result')
@login_required
def result():
    #result = 'Dummy'
    user_id = request.args.get('user_id')
    news_id = request.args.get('news_id')

    # Retrieve the result based on user_id and news_id from the database
    result = get_news_result(user_id, news_id)

    if result is not None:
        return render_template('predict/result_view.html', result=result)

    return render_template('predict/result_view.html', result = 'NOT FOUND')

src/views/user/__init__.py
from flask import Blueprint
 
user_bp = Blueprint('user', __name__, template_folder='templates', url_prefix='/user')

src/views/user/routes.py
#  src\views\auth\routes.py

from flask import render_template
from . import user_bp

@user_bp.route('/')
def predict():
    return render_template('user_view.html')

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

src/templates/home/home_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css')}}">
    <title>Landing Page</title>
  
</head>
<body>
    <div class="container">
        <div class="left-wrapper">
            <div id="logo">
                <img src="{{ url_for('static', filename='images/logo4_tp.png')}}" alt="News Check">
            </div>
            <div class="typing">
                <h1>AI Fake News Detector</h1>
                <h3><span class="auto-type"></span></h3>
            </div>
        </div>
        <div class="right-wrapper">
            <h1>Get Started</h1>
            <div class="btn">
                <a href="{{url_for('auth.login')}}" class="left-btn">
                    <button id="login-btn">Login</button>
                </a>
                <a href="{{url_for('auth.signup')}}" class="right-btn">
                    <button id="signup-btn">Sign Up</button>
                </a>
            </div>
        </div>
    </div> 
    
    <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>

    <script>
        var typed = new Typed(".auto-type", {
            strings: ["Empower yourself with the Truth!", "Navigate the news landscape with confidence!", 
            "Distinguish fact from fiction, ensuring you stay informed with accurate and credible information!"],
            typeSpeed: 150,
            backSpeed: 100,
            loop: true
        })
    </script>
</body>
</html>

src/templates/predict/predict_view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/predict.css')}}"
    />
    <title>Landing Page</title>
  </head>
  <body>
    <div class="container">
      <div class="left-wrapper">
        <div id="logo">
          <img
            src="{{ url_for('static', filename='images/logo4_tp.png')}}"
            alt="News Check"
          />
        </div>
        <div class="type-text">
          <h1>AI Fake News Detector</h1>
          <h3>Steps:</h3>
          <ul class="steps">
            <li>Enter the News in the Textbox</li>
            <li>Click on the Submit button</li>
            <li>Check the result</li>
          </ul>
        </div>
      </div>

      <div class="right-wrapper">
        <h1>AI Fake News Detector</h1>
        <form
          class="input-box"
          method="POST"
          action="{{ url_for('predict.predict') }}"
        >
          {{ form.hidden_tag() }}
          <div>
            <!-- <label >Enter news headline or copy paste the news paragraph</label> -->
            {{ form.news.label }}
            <!-- <input type="text" class="text-input"> -->
            {{ form.news(class="text-input") }} {% for error in form.news.errors
            %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          <div class="primary-btn">
            <!-- <button id="btn">Submit</button> -->
            {{ form.submit(id="btn") }}
          </div>
        </form>
        <div class="btn">
          <a href="{{url_for('auth.logout')}}" class="secondary-btn">Logout</a>
        </div>
      </div>
    </div>
  </body>
</html>

src/templates/predict/result_view.html
{% extends 'base.html'%}

{% block title %}Auth{% endblock %} 

{% block content %}
    <h1>Result: {{ result }}</h1>
{% endblock %}